name: gossip
description: A Dart library for synchronizing event streams across devices using gossip protocols.
version: 1.0.0
repository: https://github.com/neutrinographics/gossip
resolution: workspace

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  meta: ^1.11.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
